---
title: "Part 4: Making Bootstrap Inferences"
author: "Christian Pascual"
date: "4/10/2019"
output: html_document
---

# The current approach

1) Draw randomly with replacement from the data
2) Create a LASSO model from the bootstrap data
3) Store the matrix of coefficients
4) Perform the calculations needed to produce the smoothed estimate $\widetilde{\beta}$ and the smoothed standard devation $\widetilde{sd_b}$
5) Test each of the coefficients against the hypotheses:

# Code 

```{r data, message = FALSE, warning = FALSE }
library(tidyverse)
library(glmnet)
library(parallel) 
library(doParallel) 
library(foreach) 
library(iterators)

nCores = 6 # change to whatever fits your specific system
registerDoParallel(nCores)

standardize = function(col) {
  mean = mean(col)
  sd = sd(col)
  return((col - mean)/sd)
}

ds = read.csv("Down.csv") %>% 
  mutate(
    class = ifelse(Class == "Control", 0, 1)
    ) %>% 
  select(-MouseID, -Class) %>% 
  na.omit() # getting rid of nas since glmnet cannot handle missing data

ds.X = ds %>% select(-class) %>% map_df(.x = ., standardize)
ds.y = ds$class
```

```{r, helpers }
boot.count = function(idx, data) {
  counts = NULL
  for (i in 1:nrow(data)) {
    counts[i] = length(which(idx == i))
  }
  return(counts)
}
```

```{r, bootstrapping }
set.seed(8160)
# Custom function to combine multiple outputs in parallel
comb = function(x, ...) {  
  mapply(cbind, x, ..., SIMPLIFY=FALSE)
}

# Parallelize the bootstrapping
B = 1000
bs = foreach(i = 1:B, .combine = "comb") %dopar% {
  # Create the bootstrap sample
  boot.idx = sample(nrow(ds), size = nrow(ds), replace = T)
  boot.X = ds.X[boot.idx,] %>% as.matrix(.)
  boot.y = ds.y[boot.idx] %>% as.matrix(.)
  
  # Calculate the count matrix
  Yij = boot.count(boot.idx, boot.X)
  
  # Cross-validate for lambda and then fit this optimal model
  cv.lasso = cv.glmnet(boot.X, boot.y, alpha = 1, family = "binomial")
  best.lasso = glmnet(boot.X, boot.y, alpha = 1, lambda = cv.lasso$lambda.min)
  
  # Extract the coefficients and store in a matrix
  coeffs = matrix(coef(best.lasso))
  
  list(coeff.mat = coeffs, Yij.mat = Yij)
  }

# Finishing off the calculations
Y.j = rowSums(bs$Yij.mat)/B
t.j = rowSums(bs$coeff.mat)/B
t.diff = bs$coeff.mat - t.j
Yij.diff = bs$Yij.mat - Y.j
```

```{r}
# Perform this action for each coefficient
cov.mat = NULL
for (b in 1:78) {
  covs = NULL
  for (j in 1:nrow(ds)) {
    # Each individual point will have a bootstrap
    # covariance with the bootstrap statistic
    cov.j = 0
    for (i in 1:B) {
      cov.j = cov.j + ((bs$Yij.mat[j,i] - Y.j[j]) * (bs$coeff.mat[b,i] - t.j[b]))/B
    }
    covs = c(covs, cov.j)
  }
  cov.mat = rbind(cov.mat, covs)
}
```

```{r}
# With the calculated covariances for each point, 
# calculate the smooth bootstrap standard deviation
sdbs = rep(0, 78)
for (i in 1:nrow(cov.mat)) {
  sdbs[i] = (sum(cov.mat[i,] * cov.mat[i,]))^(1/2)
}

# Calculate the standard bootstrap confidence intervals
standard.std = NULL
for (i in 1:nrow(cov.mat)) {
  std = sum((1/B) * (bs$coeff.mat[i,] - mean(bs$coeff.mat[i,]))^2)^(1/2)
  standard.std = c(standard.std, std)
}

# Calculate the percentile confidence intervals
p025 = NULL
p975 = NULL
for (i in 1:nrow(cov.mat)) {
  p025 = c(p025, quantile(t.diff[i,], 0.025))
  p975 = c(p975, quantile(t.diff[i,], 0.975))
}

conf.mat = as_tibble(cbind(t.j, sdbs, standard.std, p025, p975))
conf.mat.extra = conf.mat %>% 
  mutate(
    efron.lb = t.j - qnorm(0.975) * sdbs,
    efron.ub = t.j + qnorm(0.975) * sdbs,
    is.significant = ifelse((efron.lb <= 0 & 0 <= efron.ub), FALSE, TRUE),
    idx = 1:length(sdbs)
  )
```

```{r}
# Version highlighting only the significant proteins
ggplot(data = conf.mat.extra) +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == TRUE),
             color = "blue") +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                data = subset(conf.mat.extra, is.significant == TRUE), color = "blue") +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == FALSE),
             color = "blue", alpha = 0.1) +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                color = "blue", alpha = 0.1, data = conf.mat.extra) +
  geom_errorbar(aes(x = idx, ymin = p025, ymax = p975),
                color = "red", alpha = 0.2, data = conf.mat.extra) +
  theme_bw() +
  labs(
    title = "All significant proteins, according to Efron's smoothed interval",
    x = "Protein index",
    y = "Estimated coefficient"
  )

# Version highlighting the percentile intervals
ggplot(data = conf.mat.extra) +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == TRUE),
             color = "blue", alpha = 0.1) +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                data = subset(conf.mat.extra, is.significant == TRUE), color = "blue", alpha = 0.1) +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == FALSE),
             color = "blue", alpha = 0.1) +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                color = "blue", alpha = 0.1, data = conf.mat.extra) +
  geom_errorbar(aes(x = idx, ymin = p025, ymax = p975),
                color = "red", data = conf.mat.extra) +
  theme_bw() +
  labs(
    title = "Bootstrap percentile interval",
    x = "Protein index",
    y = "Estimated coefficient"
  )

# Version highlighting how close the standard and bootstrap intervals are
ggplot(data = conf.mat.extra) +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == TRUE),
             color = "blue") +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                data = subset(conf.mat.extra, is.significant == TRUE), color = "blue") +
  geom_point(aes(x = idx + 1, y = t.j),
             color = "green", data = subset(conf.mat.extra, is.significant == TRUE)) +
  geom_errorbar(aes(x = idx + 1, ymin = t.j - qnorm(0.975) * standard.std, 
                    ymax = t.j + qnorm(0.975) * standard.std),
                color = "green", data = subset(conf.mat.extra, is.significant == TRUE)) +
  geom_point(aes(x = idx, y = t.j), data = subset(conf.mat.extra, is.significant == FALSE),
             color = "blue", alpha = 0) +
  geom_errorbar(aes(x = idx, ymin = t.j - qnorm(0.975) * sdbs, ymax = t.j + qnorm(0.975) * sdbs),
                color = "blue", alpha = 0, data = conf.mat.extra) +
  theme_bw() +
  labs(
    title = "Comparison of standard bootstrap confidence interval against Efron's",
    x = "Protein index",
    y = "Estimated coefficient"
  )
```

```{r}
# Need to extract names of significant proteins
sigs = conf.mat.extra %>% 
  mutate(protein = c("Intercept", colnames(ds.X))) %>% 
  filter(is.significant == TRUE) %>% 
  select(protein, t.j, efron.lb, efron.ub)

knitr::kable(sigs)
```

```{r}
write.csv(conf.mat.extra, "efron.sd.csv")
```

